//Add activity
export const ACTIVITY_ADD_REQUEST = 'ACTIVITY_ADD_REQUEST';
export const ACTIVITY_ADD_SUCCESS = 'ACTIVITY_ADD_SUCCESS';
export const ACTIVITY_ADD_FAIL = 'ACTIVITY_ADD_FAIL';
export const ACTIVITY_ADD_RESET = 'ACTIVITY_ADD_RESET';

//Get activity details
export const ACTIVITY_DETAILS_REQUEST = 'ACTIVITY_DETAILS_REQUEST';
export const ACTIVITY_DETAILS_SUCCESS = 'ACTIVITY_DETAILS_SUCCESS';
export const ACTIVITY_DETAILS_FAIL = 'ACTIVITY_DETAILS_FAIL';
export const ACTIVITY_DETAILS_RESET = 'ACTIVITY_DETAILS_RESET';

//Update activity
export const ACTIVITY_UPDATE_REQUEST = 'ACTIVITY_UPDATE_REQUEST';
export const ACTIVITY_UPDATE_SUCCESS = 'ACTIVITY_UPDATE_SUCCESS';
export const ACTIVITY_UPDATE_FAIL = 'ACTIVITY_UPDATE_FAIL';
export const ACTIVITY_UPDATE_RESET = 'ACTIVITY_UPDATE_RESET';

// delete activity
export const ACTIVITY_DELETE_REQUEST = 'ACTIVITY_DELETE_REQUEST';
export const ACTIVITY_DELETE_SUCCESS = 'ACTIVITY_DELETE_SUCCESS';
export const ACTIVITY_DELETE_FAIL = 'ACTIVITY_DELETE_FAIL';
export const ACTIVITY_DELETE_RESET = 'ACTIVITY_DELETE_RESET';

// get list of activity
export const ACTIVITY_LIST_REQUEST = 'ACTIVITY_LIST_REQUEST';
export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS';
export const ACTIVITY_LIST_FAIL = 'ACTIVITY_LIST_FAIL';
export const ACTIVITY_LIST_RESET = 'ACTIVITY_LIST_RESET';

// filter project activities
export const ACTIVITY_LIST_FILTER = 'ACTIVITY_LIST_FILTER';
export const ACTIVITY_LIST_FILTER_CLEAR = 'ACTIVITY_LIST_FILTER_CLEAR';

//Get list of organizations for a stakeholder
export const ACTIVITY_STAKEHOLDER_LIST_REQUEST =
	'ACTIVITY_STAKEHOLDER_LIST_REQUEST';
export const ACTIVITY_STAKEHOLDER_LIST_SUCCESS =
	'ACTIVITY_STAKEHOLDER_LIST_SUCCESS';
export const ACTIVITY_STAKEHOLDER_LIST_FAIL = 'ACTIVITY_STAKEHOLDER_LIST_FAIL';
export const ACTIVITY_STAKEHOLDER_LIST_RESET =
	'ACTIVITY_STAKEHOLDER_LIST_RESET';

//filter stakeholder activities
export const ACTIVITY_STAKEHOLDER_FILTER = 'ACTIVITY_STAKEHOLDER_FILTER';
export const ACTIVITY_STAKEHOLDER_FILTER_CLEAR =
	'ACTIVITY_STAKEHOLDER_FILTER_CLEAR';

//save activityInfo in localStorage
export const ACTIVITY_SAVE_REQUEST = 'ACTIVITY_SAVE_REQUEST';
export const ACTIVITY_SAVE_RESET = 'ACTIVITY_SAVE_RESET';
