//add commitment
export const COMMITMENT_ADD_REQUEST = 'COMMITMENT_ADD_REQUEST';
export const COMMITMENT_ADD_SUCCESS = 'COMMITMENT_ADD_SUCCESS';
export const COMMITMENT_ADD_FAIL = 'COMMITMENT_ADD_FAIL';
export const COMMITMENT_ADD_RESET = 'COMMITMENT_ADD_RESET';

//get commitment details
export const COMMITMENT_DETAILS_REQUEST = 'COMMITMENT_DETAILS_REQUEST';
export const COMMITMENT_DETAILS_SUCCESS = 'COMMITMENT_DETAILS_SUCCESS';
export const COMMITMENT_DETAILS_FAIL = 'COMMITMENT_DETAILS_FAIL';
export const COMMITMENT_DETAILS_RESET = 'COMMITMENT_DETAILS_RESET';

//update commitment
export const COMMITMENT_UPDATE_REQUEST = 'COMMITMENT_UPDATE_REQUEST';
export const COMMITMENT_UPDATE_SUCCESS = 'COMMITMENT_UPDATE_SUCCESS';
export const COMMITMENT_UPDATE_FAIL = 'COMMITMENT_UPDATE_FAIL';
export const COMMITMENT_UPDATE_RESET = 'COMMITMENT_UPDATE_RESET';

//delete commitment
export const COMMITMENT_DELETE_REQUEST = 'COMMITMENT_DELETE_REQUEST';
export const COMMITMENT_DELETE_SUCCESS = 'COMMITMENT_DELETE_SUCCESS';
export const COMMITMENT_DELETE_FAIL = 'COMMITMENT_DELETE_FAIL';
export const COMMITMENT_DELETE_RESET = 'COMMITMENT_DELETE_RESET';

//get list of commitment
export const COMMITMENT_LIST_REQUEST = 'COMMITMENT_LIST_REQUEST';
export const COMMITMENT_LIST_SUCCESS = 'COMMITMENT_LIST_SUCCESS';
export const COMMITMENT_LIST_FAIL = 'COMMITMENT_LIST_FAIL';
export const COMMITMENT_LIST_RESET = 'COMMITMENT_LIST_RESET';
