//add comment
export const COMMENT_ADD_REQUEST = 'COMMENT_ADD_REQUEST';
export const COMMENT_ADD_SUCCESS = 'COMMENT_ADD_SUCCESS';
export const COMMENT_ADD_FAIL = 'COMMENT_ADD_FAIL';
export const COMMENT_ADD_RESET = 'COMMENT_ADD_RESET';

//get comment details
export const COMMENT_DETAILS_REQUEST = 'COMMENT_DETAILS_REQUEST';
export const COMMENT_DETAILS_SUCCESS = 'COMMENT_DETAILS_SUCCESS';
export const COMMENT_DETAILS_FAIL = 'COMMENT_DETAILS_FAIL';
export const COMMENT_DETAILS_RESET = 'COMMENT_DETAILS_RESET';

//update comment
export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_UPDATE_FAIL = 'COMMENT_UPDATE_FAIL';
export const COMMENT_UPDATE_RESET = 'COMMENT_UPDATE_RESET';

//delete comment
export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';
export const COMMENT_DELETE_RESET = 'COMMENT_DELETE_RESET';

//get list of comments
export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL';
export const COMMENT_LIST_RESET = 'COMMENT_LIST_RESET';
