// add community
export const COMMUNITY_ADD_REQUEST = 'COMMUNITY_ADD_REQUEST';
export const COMMUNITY_ADD_SUCCESS = 'COMMUNITY_ADD_SUCCESS';
export const COMMUNITY_ADD_FAIL = 'COMMUNITY_ADD_FAIL';
export const COMMUNITY_ADD_RESET = 'COMMUNITY_ADD_RESET';

// get community details
export const COMMUNITY_DETAILS_REQUEST = 'COMMUNITY_DETAILS_REQUEST';
export const COMMUNITY_DETAILS_SUCCESS = 'COMMUNITY_DETAILS_SUCCESS';
export const COMMUNITY_DETAILS_FAIL = 'COMMUNITY_DETAILS_FAIL';
export const COMMUNITY_DETAILS_RESET = 'COMMUNITY_DETAILS_RESET';

// update community
export const COMMUNITY_UPDATE_REQUEST = 'COMMUNITY_UPDATE_REQUEST';
export const COMMUNITY_UPDATE_SUCCESS = 'COMMUNITY_UPDATE_SUCCESS';
export const COMMUNITY_UPDATE_FAIL = 'COMMUNITY_UPDATE_FAIL';
export const COMMUNITY_UPDATE_RESET = 'COMMUNITY_UPDATE_RESET';

// delete community
export const COMMUNITY_DELETE_REQUEST = 'COMMUNITY_DELETE_REQUEST';
export const COMMUNITY_DELETE_SUCCESS = 'COMMUNITY_DELETE_SUCCESS';
export const COMMUNITY_DELETE_FAIL = 'COMMUNITY_DELETE_FAIL';
export const COMMUNITY_DELETE_RESET = 'COMMUNITY_DELETE_RESET';

// get list of communities
export const COMMUNITY_LIST_REQUEST = 'COMMUNITY_LIST_REQUEST';
export const COMMUNITY_LIST_SUCCESS = 'COMMUNITY_LIST_SUCCESS';
export const COMMUNITY_LIST_FAIL = 'COMMUNITY_LIST_FAIL';
export const COMMUNITY_LIST_RESET = 'COMMUNITY_LIST_RESET';
