// add location
export const DOCUMENT_ADD_REQUEST = 'DOCUMENT_ADD_REQUEST';
export const DOCUMENT_ADD_SUCCESS = 'DOCUMENT_ADD_SUCCESS';
export const DOCUMENT_ADD_FAIL = 'DOCUMENT_ADD_FAIL';
export const DOCUMENT_ADD_RESET = 'DOCUMENT_ADD_RESET';

// get DOCUMENT details
export const DOCUMENT_DETAILS_REQUEST = 'DOCUMENT_DETAILS_REQUEST';
export const DOCUMENT_DETAILS_SUCCESS = 'DOCUMENT_DETAILS_SUCCESS';
export const DOCUMENT_DETAILS_FAIL = 'DOCUMENT_DETAILS_FAIL';
export const DOCUMENT_DETAILS_RESET = 'DOCUMENT_DETAILS_RESET';

// update DOCUMENT
export const DOCUMENT_UPDATE_REQUEST = 'DOCUMENT_UPDATE_REQUEST';
export const DOCUMENT_UPDATE_SUCCESS = 'DOCUMENT_UPDATE_SUCCESS';
export const DOCUMENT_UPDATE_FAIL = 'DOCUMENT_UPDATE_FAIL';
export const DOCUMENT_UPDATE_RESET = 'DOCUMENT_UPDATE_RESET';

// delete DOCUMENT
export const DOCUMENT_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST';
export const DOCUMENT_DELETE_SUCCESS = 'DOCUMENT_DELETE_SUCCESS';
export const DOCUMENT_DELETE_FAIL = 'DOCUMENT_DELETE_FAIL';
export const DOCUMENT_DELETE_RESET = 'DOCUMENT_DELETE_RESET';

// get list of project documents
export const DOCUMENT_LIST_PROJECT_REQUEST = 'DOCUMENT_LIST_PROJECT_REQUEST';
export const DOCUMENT_LIST_PROJECT_SUCCESS = 'DOCUMENT_LIST_PROJECT_SUCCESS';
export const DOCUMENT_LIST_PROJECT_FAIL = 'DOCUMENT_LIST_PROJECT_FAIL';
export const DOCUMENT_LIST_PROJECT_RESET = 'DOCUMENT_LIST_PROJECT_RESET';

// get list of location documents
export const DOCUMENT_LIST_LOCATION_REQUEST = 'DOCUMENT_LIST_LOCATION_REQUEST';
export const DOCUMENT_LIST_LOCATION_SUCCESS = 'DOCUMENT_LIST_LOCATION_SUCCESS';
export const DOCUMENT_LIST_LOCATION_FAIL = 'DOCUMENT_LIST_LOCATION_FAIL';
export const DOCUMENT_LIST_LOCATION_RESET = 'DOCUMENT_LIST_LOCATION_RESET';

// get list of organization documents
export const DOCUMENT_LIST_ORGANIZATION_REQUEST =
	'DOCUMENT_LIST_ORGANIZATION_REQUEST';
export const DOCUMENT_LIST_ORGANIZATION_SUCCESS =
	'DOCUMENT_LIST_ORGANIZATION_SUCCESS';
export const DOCUMENT_LIST_ORGANIZATION_FAIL =
	'DOCUMENT_LIST_ORGANIZATION_FAIL';
export const DOCUMENT_LIST_ORGANIZATION_RESET =
	'DOCUMENT_LIST_ORGANIZATION_RESET';

// get list of stakeholder documents
export const DOCUMENT_LIST_STAKEHOLDER_REQUEST =
	'DOCUMENT_LIST_STAKEHOLDER_REQUEST';
export const DOCUMENT_LIST_STAKEHOLDER_SUCCESS =
	'DOCUMENT_LIST_STAKEHOLDER_SUCCESS';
export const DOCUMENT_LIST_STAKEHOLDER_FAIL = 'DOCUMENT_LIST_STAKEHOLDER_FAIL';
export const DOCUMENT_LIST_STAKEHOLDER_RESET =
	'DOCUMENT_LIST_STAKEHOLDER_RESET';
