//Get geocode
export const GEOCODE_FETCH_REQUEST = 'GEOCODE_FETCH_REQUEST';
export const GEOCODE_FETCH_SUCCESS = 'GEOCODE_FETCH_SUCCESS';
export const GEOCODE_FETCH_FAIL = 'GEOCODE_FETCH_FAIL';
export const GEOCODE_FETCH_RESET = 'GEOCODE_FETCH_RESET';