//Add influence
export const INFLUENCE_ADD_REQUEST = 'INFLUENCE_ADD_REQUEST';
export const INFLUENCE_ADD_SUCCESS = 'INFLUENCE_ADD_SUCCESS';
export const INFLUENCE_ADD_FAIL = 'INFLUENCE_ADD_FAIL';
export const INFLUENCE_ADD_RESET = 'INFLUENCE_ADD_RESET';

//Get influence details
export const INFLUENCE_DETAILS_REQUEST = 'INFLUENCE_DETAILS_REQUEST';
export const INFLUENCE_DETAILS_SUCCESS = 'INFLUENCE_DETAILS_SUCCESS';
export const INFLUENCE_DETAILS_FAIL = 'INFLUENCE_DETAILS_FAIL';
export const INFLUENCE_DETAILS_RESET = 'INFLUENCE_DETAILS_RESET';

//Delete influence
export const INFLUENCE_DELETE_REQUEST = 'INFLUENCE_DELETE_REQUEST';
export const INFLUENCE_DELETE_SUCCESS = 'INFLUENCE_DELETE_SUCCESS';
export const INFLUENCE_DELETE_FAIL = 'INFLUENCE_DELETE_FAIL';
export const INFLUENCE_DELETE_RESET = 'INFLUENCE_DELETE_RESET';

//Get list of influences
export const INFLUENCE_LIST_REQUEST = 'INFLUENCE_LIST_REQUEST';
export const INFLUENCE_LIST_SUCCESS = 'INFLUENCE_LIST_SUCCESS';
export const INFLUENCE_LIST_FAIL = 'INFLUENCE_LIST_FAIL';
export const INFLUENCE_LIST_RESET = 'INFLUENCE_LIST_RESET';

export const INFLUENCE_LIST_FILTER = 'INFLUENCE_LIST_FILTER';
export const INFLUENCE_LIST_FILTER_CLEAR =
	'INFLUENCE_LIST_FILTER_CLEAR';