// add landownership
export const LANDOWNERSHIP_ADD_REQUEST = 'LANDOWNERSHIP_ADD_REQUEST';
export const LANDOWNERSHIP_ADD_SUCCESS = 'LANDOWNERSHIP_ADD_SUCCESS';
export const LANDOWNERSHIP_ADD_FAIL = 'LANDOWNERSHIP_ADD_FAIL';
export const LANDOWNERSHIP_ADD_RESET = 'LANDOWNERSHIP_ADD_RESET';

// get landownership details
export const LANDOWNERSHIP_DETAILS_REQUEST = 'LANDOWNERSHIP_DETAILS_REQUEST';
export const LANDOWNERSHIP_DETAILS_SUCCESS = 'LANDOWNERSHIP_DETAILS_SUCCESS';
export const LANDOWNERSHIP_DETAILS_FAIL = 'LANDOWNERSHIP_DETAILS_FAIL';
export const LANDOWNERSHIP_DETAILS_RESET = 'LANDOWNERSHIP_DETAILS_RESET';

// update landownership
export const LANDOWNERSHIP_UPDATE_REQUEST = 'LANDOWNERSHIP_UPDATE_REQUEST';
export const LANDOWNERSHIP_UPDATE_SUCCESS = 'LANDOWNERSHIP_UPDATE_SUCCESS';
export const LANDOWNERSHIP_UPDATE_FAIL = 'LANDOWNERSHIP_UPDATE_FAIL';
export const LANDOWNERSHIP_UPDATE_RESET = 'LANDOWNERSHIP_UPDATE_RESET';

// delete landownership
export const LANDOWNERSHIP_DELETE_REQUEST = 'LANDOWNERSHIP_DELETE_REQUEST';
export const LANDOWNERSHIP_DELETE_SUCCESS = 'LANDOWNERSHIP_DELETE_SUCCESS';
export const LANDOWNERSHIP_DELETE_FAIL = 'LANDOWNERSHIP_DELETE_FAIL';
export const LANDOWNERSHIP_DELETE_RESET = 'LANDOWNERSHIP_DELETE_RESET';

// get list of landownership
export const LANDOWNERSHIP_LIST_REQUEST = 'LANDOWNERSHIP_LIST_REQUEST';
export const LANDOWNERSHIP_LIST_SUCCESS = 'LANDOWNERSHIP_LIST_SUCCESS';
export const LANDOWNERSHIP_LIST_FAIL = 'LANDOWNERSHIP_LIST_FAIL';
export const LANDOWNERSHIP_LIST_RESET = 'LANDOWNERSHIP_LIST_RESET';
