// add location
export const LOCATION_ADD_REQUEST = 'LOCATION_ADD_REQUEST';
export const LOCATION_ADD_SUCCESS = 'LOCATION_ADD_SUCCESS';
export const LOCATION_ADD_FAIL = 'LOCATION_ADD_FAIL';
export const LOCATION_ADD_RESET = 'LOCATION_ADD_RESET';

// get location details
export const LOCATION_DETAILS_REQUEST = 'LOCATION_DETAILS_REQUEST';
export const LOCATION_DETAILS_SUCCESS = 'LOCATION_DETAILS_SUCCESS';
export const LOCATION_DETAILS_FAIL = 'LOCATION_DETAILS_FAIL';
export const LOCATION_DETAILS_RESET = 'LOCATION_DETAILS_RESET';

// update location
export const LOCATION_UPDATE_REQUEST = 'LOCATION_UPDATE_REQUEST';
export const LOCATION_UPDATE_SUCCESS = 'LOCATION_UPDATE_SUCCESS';
export const LOCATION_UPDATE_FAIL = 'LOCATION_UPDATE_FAIL';
export const LOCATION_UPDATE_RESET = 'LOCATION_UPDATE_RESET';

// delete location
export const LOCATION_DELETE_REQUEST = 'LOCATION_DELETE_REQUEST';
export const LOCATION_DELETE_SUCCESS = 'LOCATION_DELETE_SUCCESS';
export const LOCATION_DELETE_FAIL = 'LOCATION_DELETE_FAIL';
export const LOCATION_DELETE_RESET = 'LOCATION_DELETE_RESET';

// get list of locations
export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST';
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS';
export const LOCATION_LIST_FAIL = 'LOCATION_LIST_FAIL';
export const LOCATION_LIST_RESET = 'LOCATION_LIST_RESET';

// filter project locations
export const LOCATION_LIST_FILTER = 'LOCATION_LIST_FILTER';
export const LOCATION_LIST_FILTER_CLEAR = 'LOCATION_LIST_FILTER_CLEAR';

// get list of locations for a user
export const LOCATION_USER_LIST_REQUEST = 'LOCATION_USER_LIST_REQUEST';
export const LOCATION_USER_LIST_SUCCESS = 'LOCATION_USER_LIST_SUCCESS';
export const LOCATION_USER_LIST_FAIL = 'LOCATION_USER_LIST_FAIL';
export const LOCATION_USER_LIST_RESET = 'LOCATION_USER_LIST_RESET';

// drop-down list of communities
export const LOCATION_DROPDOWN_REQUEST = 'LOCATION_DROPDOWN_REQUEST';
export const LOCATION_DROPDOWN_SUCCESS = 'LOCATION_DROPDOWN_SUCCESS';
export const LOCATION_DROPDOWN_FAIL = 'LOCATION_DROPDOWN_FAIL';
export const LOCATION_DROPDOWN_RESET = 'LOCATION_DROPDOWN_RESET';

// assign locations to dropdown
export const LOCATION_ASSIGN_REQUEST = 'LOCATION_ASSIGN_REQUEST';
export const LOCATION_ASSIGN_SUCCESS = 'LOCATION_ASSIGN_SUCCESS';
export const LOCATION_ASSIGN_FAIL = 'LOCATION_ASSIGN_FAIL';
export const LOCATION_ASSIGN_RESET = 'LOCATION_ASSIGN_RESET';

// filter project locations for a user
export const LOCATION_USER_LIST_FILTER = 'LOCATION_USER_LIST_FILTER';
export const LOCATION_USER_LIST_FILTER_CLEAR =
	'USER_LOCATION_LIST_FILTER_CLEAR';

// save locationId to localStorage to use for retreiving stakeholders and organizations
export const LOCATION_ID_REQUEST = 'LOCATION_ID_REQUEST';
