//Add NEWS
export const NEWS_ADD_REQUEST = 'NEWS_ADD_REQUEST';
export const NEWS_ADD_SUCCESS = 'NEWS_ADD_SUCCESS';
export const NEWS_ADD_FAIL = 'NEWS_ADD_FAIL';
export const NEWS_ADD_RESET = 'NEWS_ADD_RESET';

//Get NEWS details
export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST';
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS';
export const NEWS_DETAILS_FAIL = 'NEWS_DETAILS_FAIL';
export const NEWS_DETAILS_RESET = 'NEWS_DETAILS_RESET';

//Update NEWS
export const NEWS_UPDATE_REQUEST = 'NEWS_UPDATE_REQUEST';
export const NEWS_UPDATE_SUCCESS = 'NEWS_UPDATE_SUCCESS';
export const NEWS_UPDATE_FAIL = 'NEWS_UPDATE_FAIL';
export const NEWS_UPDATE_RESET = 'NEWS_UPDATE_RESET';

// delete NEWS
export const NEWS_DELETE_REQUEST = 'NEWS_DELETE_REQUEST';
export const NEWS_DELETE_SUCCESS = 'NEWS_DELETE_SUCCESS';
export const NEWS_DELETE_FAIL = 'NEWS_DELETE_FAIL';
export const NEWS_DELETE_RESET = 'NEWS_DELETE_RESET';

// get list of NEWS for a project
export const NEWS_LIST_PROJECT_REQUEST = 'NEWS_LIST_PROJECT_REQUEST';
export const NEWS_LIST_PROJECT_SUCCESS = 'NEWS_LIST_PROJECT_SUCCESS';
export const NEWS_LIST_PROJECT_FAIL = 'NEWS_LIST_PROJECT_FAIL';
export const NEWS_LIST_PROJECT_RESET = 'NEWS_LIST_PROJECT_RESET';

// get list of NEWS for a community
export const NEWS_LIST_LOCATION_REQUEST = 'NEWS_LIST_LOCATION_REQUEST';
export const NEWS_LIST_LOCATION_SUCCESS = 'NEWS_LIST_LOCATION_SUCCESS';
export const NEWS_LIST_LOCATION_FAIL = 'NEWS_LIST_LOCATION_FAIL';
export const NEWS_LIST_LOCATION_RESET = 'NEWS_LIST_LOCATION_RESET';

// get list of NEWS for a stakeholder
export const NEWS_LIST_STAKEHOLDER_REQUEST = 'NEWS_LIST_STAKEHOLDER_REQUEST';
export const NEWS_LIST_STAKEHOLDER_SUCCESS = 'NEWS_LIST_STAKEHOLDER_SUCCESS';
export const NEWS_LIST_STAKEHOLDER_FAIL = 'NEWS_LIST_STAKEHOLDER_FAIL';
export const NEWS_LIST_STAKEHOLDER_RESET = 'NEWS_LIST_STAKEHOLDER_RESET';

// get list of NEWS for an organization
export const NEWS_LIST_ORGANIZATION_REQUEST = 'NEWS_LIST_ORGANIZATION_REQUEST';
export const NEWS_LIST_ORGANIZATION_SUCCESS = 'NEWS_LIST_ORGANIZATION_SUCCESS';
export const NEWS_LIST_ORGANIZATION_FAIL = 'NEWS_LIST_ORGANIZATION_FAIL';
export const NEWS_LIST_ORGANIZATION_RESET = 'NEWS_LIST_ORGANIZATION_RESET';
