// Add organization
export const ORGANIZATION_ADD_REQUEST = 'ORGANIZATION_ADD_REQUEST';
export const ORGANIZATION_ADD_SUCCESS = 'ORGANIZATION_ADD_SUCCESS';
export const ORGANIZATION_ADD_FAIL = 'ORGANIZATION_ADD_FAIL';
export const ORGANIZATION_ADD_RESET = 'ORGANIZATION_ADD_RESET';

// Get organization details
export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST';
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_SUCCESS';
export const ORGANIZATION_DETAILS_FAIL = 'ORGANIZATION_DETAILS_FAIL';
export const ORGANIZATION_DETAILS_RESET = 'ORGANIZATION_DETAILS_RESET';

// Update organization
export const ORGANIZATION_UPDATE_REQUEST = 'ORGANIZATION_UPDATE_REQUEST';
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS';
export const ORGANIZATION_UPDATE_FAIL = 'ORGANIZATION_UPDATE_FAIL';
export const ORGANIZATION_UPDATE_RESET = 'ORGANIZATION_UPDATE_RESET';

// Delete organization
export const ORGANIZATION_DELETE_REQUEST = 'ORGANIZATION_DELETE_REQUEST';
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_SUCCESS';
export const ORGANIZATION_DELETE_FAIL = 'ORGANIZATION_DELETE_FAIL';
export const ORGANIZATION_DELETE_RESET = 'ORGANIZATION_DELETE_RESET';

// Get list of organization for a location or community
export const ORGANIZATION_LOCATION_LIST_REQUEST =
	'ORGANIZATION_LOCATION_LIST_REQUEST';
export const ORGANIZATION_LOCATION_LIST_SUCCESS =
	'ORGANIZATION_LOCATION_LIST_SUCCESS';
export const ORGANIZATION_LOCATION_LIST_FAIL =
	'ORGANIZATION_LOCATION_LIST_FAIL';
export const ORGANIZATION_LOCATION_LIST_RESET =
	'ORGANIZATION_LOCATION_LIST_RESET';

// Get list of organizations for a stakeholder
export const ORGANIZATION_STAKEHOLDER_LIST_REQUEST =
	'ORGANIZATION_STAKEHOLDER_LIST_REQUEST';
export const ORGANIZATION_STAKEHOLDER_LIST_SUCCESS =
	'ORGANIZATION_STAKEHOLDER_LIST_SUCCESS';
export const ORGANIZATION_STAKEHOLDER_LIST_FAIL =
	'ORGANIZATION_STAKEHOLDER_LIST_FAIL';
export const ORGANIZATION_STAKEHOLDER_LIST_RESET =
	'ORGANIZATION_STAKEHOLDER_LIST_RESET';

// Get list of organizations for a project
export const ORGANIZATION_PROJECT_LIST_REQUEST =
	'ORGANIZATION_PROJECT_LIST_REQUEST';
export const ORGANIZATION_PROJECT_LIST_SUCCESS =
	'ORGANIZATION_PROJECT_LIST_SUCCESS';
export const ORGANIZATION_PROJECT_LIST_FAIL = 'ORGANIZATION_PROJECT_LIST_FAIL';
export const ORGANIZATION_PROJECT_LIST_RESET =
	'ORGANIZATION_PROJECT_LIST_RESET';

// filter project organizations
export const ORGANIZATION_PROJECT_FILTER = 'ORGANIZATION_PROJECT_FILTER';
export const ORGANIZATION_PROJECT_FILTER_CLEAR =
	'ORGANIZATION_PROJECT_FILTER_CLEAR';

// filter stakeholder organizations
export const ORGANIZATION_STAKEHOLDER_FILTER =
	'ORGANIZATION_STAKEHOLDER_FILTER';
export const ORGANIZATION_STAKEHOLDER_FILTER_CLEAR =
	'ORGANIZATION_STAKEHOLDER_FILTER_CLEAR';

// get list of updated organizations
export const ORGANIZAION_UPDATED_LIST_REQUEST =
	'ORGANIZAION_UPDATED_LIST_REQUEST';
export const ORGANIZAION_UPDATED_LIST_SUCCESS =
	'ORGANIZAION_UPDATED_LIST_SUCCESS';
export const ORGANIZAION_UPDATED_LIST_FAIL = 'ORGANIZAION_UPDATED_LIST_FAIL';
export const ORGANIZAION_UPDATED_LIST_RESET = 'ORGANIZAION_UPDATED_LIST_RESET';

// drop-down list of organizations
export const ORGANIZATION_DROPDOWN_REQUEST = 'ORGANIZATION_DROPDOWN_REQUEST';
export const ORGANIZATION_DROPDOWN_SUCCESS = 'ORGANIZATION_DROPDOWN_SUCCESS';
export const ORGANIZATION_DROPDOWN_FAIL = 'ORGANIZATION_DROPDOWN_FAIL';
export const ORGANIZATION_DROPDOWN_RESET = 'ORGANIZATION_DROPDOWN_RESET';

// Assign organizations
export const ORGANIZATION_ASSIGNMENT_REQUEST =
	'ORGANIZATION_ASSIGNMENT_REQUEST';
export const ORGANIZATION_ASSIGNMENT_SUCCESS =
	'ORGANIZATION_ASSIGNMENT_SUCCESS';
export const ORGANIZATION_ASSIGNMENT_FAIL = 'ORGANIZATION_ASSIGNMENT_FAIL';
export const ORGANIZATION_ASSIGNMENT_RESET = 'ORGANIZATION_ASSIGNMENT_RESET';
