//add stakeholder
export const STAKEHOLDER_ADD_REQUEST = 'STAKEHOLDER_ADD_REQUEST';
export const STAKEHOLDER_ADD_SUCCESS = 'STAKEHOLDER_ADD_SUCCESS';
export const STAKEHOLDER_ADD_FAIL = 'STAKEHOLDER_ADD_FAIL';
export const STAKEHOLDER_ADD_RESET = 'STAKEHOLDER_ADD_FAIL';

//get stakeholder details
export const STAKEHOLDER_DETAILS_REQUEST = 'STAKEHOLDER_DETAILS_REQUEST';
export const STAKEHOLDER_DETAILS_SUCCESS = 'STAKEHOLDER_DETAILS_SUCCESS';
export const STAKEHOLDER_DETAILS_FAIL = 'STAKEHOLDER_DETAILS_FAIL';
export const STAKEHOLDER_DETAILS_RESET = 'STAKEHOLDER_DETAILS_RESET';

//update stakeholder
export const STAKEHOLDER_UPDATE_REQUEST = 'STAKEHOLDER_UPDATE_REQUEST';
export const STAKEHOLDER_UPDATE_SUCCESS = 'STAKEHOLDER_UPDATE_SUCCESS';
export const STAKEHOLDER_UPDATE_FAIL = 'STAKEHOLDER_UPDATE_FAIL';
export const STAKEHOLDER_UPDATE_RESET = 'STAKEHOLDER_UPDATE_RESET';

//delete stakeholder
export const STAKEHOLDER_DELETE_REQUEST = 'STAKEHOLDER_DELETE_REQUEST';
export const STAKEHOLDER_DELETE_SUCCESS = 'STAKEHOLDER_DELETE_SUCCESS';
export const STAKEHOLDER_DELETE_FAIL = 'STAKEHOLDER_DELETE_FAIL';
export const STAKEHOLDER_DELETE_RESET = 'STAKEHOLDER_DELETE_RESET';

//get stakeholder list
export const STAKEHOLDER_LIST_REQUEST = 'STAKEHOLDER_LIST_REQUEST';
export const STAKEHOLDER_LIST_SUCCESS = 'STAKEHOLDER_LIST_SUCCESS';
export const STAKEHOLDER_LIST_FAIL = 'STAKEHOLDER_LIST_FAIL';
export const STAKEHOLDER_LIST_RESET = 'STAKEHOLDER_LIST_RESET';

//filter stakeholder list
export const STAKEHOLDER_PROJECT_FILTER = 'STAKEHOLDER_PROJECT_FILTER';
export const STAKEHOLDER_PROJECT_FILTER_CLEAR =
	'STAKEHOLDER_PROJECT_FILTER_CLEAR';

//get stakeholder list
export const STAKEHOLDER_USER_LIST_REQUEST = 'STAKEHOLDER_USER_LIST_REQUEST';
export const STAKEHOLDER_USER_LIST_SUCCESS = 'STAKEHOLDER_USER_LIST_SUCCESS';
export const STAKEHOLDER_USER_LIST_FAIL = 'STAKEHOLDER_USER_LIST_FAIL';
export const STAKEHOLDER_USER_LIST_RESET = 'STAKEHOLDER_USER_LIST_RESET';

//filter stakeholder list
export const STAKEHOLDER_USER_FILTER = 'STAKEHOLDER_USER_FILTER';
export const STAKEHOLDER_USER_FILTER_CLEAR = 'STAKEHOLDER_USER_FILTER_CLEAR';

//get stakeholder list for a location
export const STAKEHOLDER_LOCATION_LIST_REQUEST =
	'STAKEHOLDER_LOCATION_LIST_REQUEST';
export const STAKEHOLDER_LOCATION_LIST_SUCCESS =
	'STAKEHOLDER_LOCATION_LIST_SUCCESS';
export const STAKEHOLDER_LOCATION_LIST_FAIL = 'STAKEHOLDER_LOCATION_LIST_FAIL';
export const STAKEHOLDER_LOCATION_LIST_RESET =
	'STAKEHOLDER_LOCATION_LIST_RESET';

//filter stakeholder list
export const STAKEHOLDER_LOCATION_FILTER = 'STAKEHOLDER_LOCATION_FILTER';
export const STAKEHOLDER_LOCATION_FILTER_CLEAR =
	'STAKEHOLDER_LOCATION_FILTER_CLEAR';

//get stakeholder list for a project
export const STAKEHOLDER_PROJECT_LIST_REQUEST =
	'STAKEHOLDER_PROJECT_LIST_REQUEST';
export const STAKEHOLDER_PROJECT_LIST_SUCCESS =
	'STAKEHOLDER_PROJECT_LIST_SUCCESS';
export const STAKEHOLDER_PROJECT_LIST_FAIL = 'STAKEHOLDER_PROJECT_LIST_FAIL';
export const STAKEHOLDER_PROJECT_LIST_RESET = 'STAKEHOLDER_PROJECT_LIST_RESET';

//filter stakeholder list
export const STAKEHOLDER_PROJECT_LIST_FILTER =
	'STAKEHOLDER_PROJECT_LIST_FILTER';
export const STAKEHOLDER_PROJECT_LIST_FILTER_CLEAR =
	'STAKEHOLDER_PROJECT_LIST_FILTER_CLEAR';

// assign stakeholders
export const STAKEHOLDER_ASSIGN_REQUEST = 'STAKEHOLDER_ASSIGN_REQUEST';
export const STAKEHOLDER_ASSIGN_SUCCESS = 'STAKEHOLDER_ASSIGN_SUCCESS';
export const STAKEHOLDER_ASSIGN_FAIL = 'STAKEHOLDER_ASSIGN_FAIL';
export const STAKEHOLDER_ASSIGN_RESET = 'STAKEHOLDER_ASSIGN_RESET';

//save stakeholderInfo in localStorage
export const STAKEHOLDER_SAVE_REQUEST = 'STAKEHOLDER_SAVE_REQUEST';
export const STAKEHOLDER_SAVE_RESET = 'STAKEHOLDER_SAVE_RESET';

// drop-down list of stakeholders
export const STAKEHOLDER_DROPDOWN_REQUEST = 'STAKEHOLDER_DROPDOWN_REQUEST';
export const STAKEHOLDER_DROPDOWN_SUCCESS = 'STAKEHOLDER_DROPDOWN_SUCCESS';
export const STAKEHOLDER_DROPDOWN_FAIL = 'STAKEHOLDER_DROPDOWN_FAIL';
export const STAKEHOLDER_DROPDOWN_RESET = 'STAKEHOLDER_DROPDOWN_RESET';
